### ISSUE TITLE
Soo.... Stil active?

### ISSUE THREAD

**Issue by Kerwood** [fabrix-app/fabrix#34]
Hi.. Is this project still active ? Would it be safe for me to create a new project and learn this frame work or is Fabrix slowly dying?
Sorry for creating an issue, but the Gitter link was giving an 404 (https://gitter.im/fabrix-app/fabrix).

**Comment by Kerwood** [comment]
Also.. The guide here https://fabrix.app/docs/en/start.html doesn't really match what you get after installing `fab-cli` with `npm install -g @fabrix/fab-cli`

**Comment by scott-wyatt** [comment]
Hi! Still very active, the core is small which is why there isn’t a ton of activity on it! I’ll fix the link to the Gitter. Cheers!

**Comment by scott-wyatt** [comment]
[This is the gitter link](https://gitter.im/fabrix-app/Lobby).  The CLI still needs some love, but i'd recommend the [example app](https://github.com/fabrix-app/example-app) as we get the CLI up to spec. I'm closing this for now, feel free to post here or on gitter if you need anything
